<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DellLaptop" failures="1" tests="5" name="App" time="26.602" errors="0" timestamp="2022-02-13T01:05:51 EST">
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="forgotPassword" time="0.232"/>
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="loginErrorMessage" time="0.503"/>
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="loginTest" time="3.057"/>
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="rememberMe" time="7.465">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.salesforcenew.testCases.LoginTest.rememberMe(LoginTest.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- rememberMe -->
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="validateloginErrorMessage" time="0.288"/>
</testsuite> <!-- App -->
